#!/bin/bash

# Error flags configuration for bash
set -o errexit
set -o pipefail
set -o nounset

# Launching migrations and the flask development server
uvicorn main:app --reload --host 0.0.0.0 --port 8000